In [179]:
#import data
import csv
import pandas as pd

df_train=pd.read_csv('../data/01_train/train.tsv', sep='\t',
            header=0,
            names = ["Nr","Wort","Typ1","Typ2"],
            quoting=csv.QUOTE_NONE                     ,
                     keep_default_na=False,
                     encoding='utf-8')

df_train = df_train.drop(df_train[df_train['Nr']=='#'].index)
df_train=df_train.reset_index(drop=False)




In [180]:
'Label dict filter'
outside =0
label_dict = {
    'B-LOC': 1,
    'I-LOC': 2,
    'B-PER': 3,
    'I-PER': 4,
    'B-ORG': 5,
    'I-ORG': 6,
    'B-LOCderiv': outside,
    "B-LOCpart": outside,
    'B-ORGderiv': outside,
    'B-ORGpart': outside,
    'B-OTH': outside,
    'B-OTHderiv': outside,
    'B-OTHpart': outside,
    'B-PERderiv': outside,
    'B-PERpart': outside,
    'I-LOCderiv': outside,
    'I-LOCpart': outside,
    'I-ORGpart': outside,
    'I-OTH': outside,
    'I-OTHderiv': outside,
    'I-OTHpart': outside,
    'I-PERderiv': outside,
    'I-PERpart': outside,
    'O': outside
}



tokens=[]
labels=[]
ids=[]

sentence_token=[]
sentence_labels=[]
sentence_ids=[]

i=0

id=0
for j in range(0, len(df_train)):
    if i > 0 and df_train.Nr[j] == '1':
        tokens.append(sentence_token)
        labels.append(sentence_labels)

        sentence_token, sentence_labels = [], []
        ids.append(id)
        id = id + 1

    sentence_token.append(str(df_train.Wort[j]))
    # sentence_labels.append(df_train.Typ1[j])
    sentence_labels.append(label_dict.get(df_train.Typ1[j]))

    i = i + 1

In [181]:
'Data Preprocessing'


'Data Preprocessing'

In [182]:
'label alignment'

'label alignment'

In [183]:
from datasets.dataset_dict import DatasetDict
from datasets import Dataset


conll = {'train':Dataset.from_dict({'id':ids,'tokens':tokens,'ner_tags':labels})
    ,'validation':Dataset.from_dict({'id':ids[10:11],'tokens':tokens[10:11],'ner_tags':labels[10:11]})
     #'test':Dataset.from_dict({'label':y_test,'text':x_test})
     }

In [184]:
from datasets import Dataset, ClassLabel, Sequence, Features, Value


d = {'id':ids ,'ner_tags': labels, 'tokens': tokens}
# define number of tags and their names
tags = ClassLabel(num_classes=7, names=['O', 'B-PER', 'I-PER', 'B-ORG', 'I-ORG', 'B-LOC', 'I-LOC'])
# create dataset
ds ={'train':     Dataset.from_dict(mapping=d, features=Features({"ner_tags":Sequence(tags),  'id': Value(dtype='string'),  'tokens': Sequence(feature=Value(dtype='string'))})),
     'validation':Dataset.from_dict(mapping=d, features=Features({"ner_tags":Sequence(tags),  'id': Value(dtype='string'),  'tokens': Sequence(feature=Value(dtype='string'))}))

     }
# access ClassLabel feature - 0 returns tag "O", 1 returns "B-PER" etc
#ds['train'].features["ner_tags"].feature.int2str(0)
#conll=ds
conll=ds

In [185]:
labels

[[3, 0, 0, 0, 5, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 3, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [5, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 5, 6, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  3,
  4,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  3,
  4,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0

In [186]:
#test
print(conll['train'][0]['ner_tags'])
print(conll['train'][0]['tokens'])

# print(conll['train'][1]['ner_tags'])
# print(conll['train'][1]['tokens'])
#
# print(conll['train'][2]['ner_tags'])
# print(conll['train'][2]['tokens'])
#
# print(conll['train'][3]['ner_tags'])
# print(conll['train'][3]['tokens'])
#
# print(conll['train'][4]['ner_tags'])
# print(conll['train'][4]['tokens'])
#
# print(conll['train'].features['ner_tags'])




[3, 0, 0, 0, 5, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
['Schartau', 'sagte', 'dem', '"', 'Tagesspiegel', '"', 'vom', 'Freitag', ',', 'Fischer', 'sei', '"', 'in', 'einer', 'Weise', 'aufgetreten', ',', 'die', 'alles', 'andere', 'als', 'überzeugend', 'war', '"', '.']


In [187]:
from transformers import AutoTokenizer

'inferenz'
model_name = 'deepset/gbert-base'
# model_name='jplu/tf-xlm-r-ner-40-lang'
# model_name='Davlan/bert-base-multilingual-cased-ner-hrl'
tokenizer = AutoTokenizer.from_pretrained(model_name)
inputs = tokenizer(conll['train'][0]['tokens'], is_split_into_words=True)
inputs.tokens()

['[CLS]',
 'Schar',
 '##ta',
 '##u',
 'sagte',
 'dem',
 '"',
 'Tages',
 '##spiegel',
 '"',
 'vom',
 'Freitag',
 ',',
 'Fischer',
 'sei',
 '"',
 'in',
 'einer',
 'Weise',
 'aufgetreten',
 ',',
 'die',
 'alles',
 'andere',
 'als',
 'überzeugen',
 '##d',
 'war',
 '"',
 '.',
 '[SEP]']

In [188]:


def tokenize_and_align_labels(sequence_batch):
    # tokenize pre-tokenized sequences
    # long sequences will be truncated to respect the maximum token length of the language model (usually 512)
    tokenized_sequences = tokenizer(sequence_batch['tokens'], truncation=True, is_split_into_words=True)

    labels = []
    # iterate over pre-tokenized tokens of single sequences
    for i, label in enumerate(sequence_batch['ner_tags']):
        # get associated word ids of the subtokens
        # if a token has multiple subtokens, then each subtoken is associated with the token's word id
        word_ids = tokenized_sequences.word_ids(batch_index=i)
        previous_word_idx = None
        label_ids = []
        # iterate over subtokens
        for word_idx in word_ids:
            # special tokens (e.g. [CLS], [SEP]) get label id -100 -> loss function will ignore them
            if word_idx is None:
                label_ids.append(-100)
            # if the first subtoken of the next token is encountered, then associate the token's ner label with the subtoken
            # FIXME what if two consecutive tokens are identical (e.g. "is this a really really bad?")?
            elif word_idx != previous_word_idx:
                label_ids.append(label[word_idx])
            # consecutive subtokens will be ignored
            else:
                label_ids.append(-100)
            # memorize the current word
            previous_word_idx = word_idx
        # add labels of the current sequence to the list of labels of the batch
        labels.append(label_ids)

    # update batch labels
    tokenized_sequences['labels'] = labels
    return tokenized_sequences

In [189]:
# # test
# example_ner_tag=conll['train'][0]['ner_tags']
# print(example_ner_tag)
# exampletokens=conll['train'][0]['tokens']
# print(exampletokens)
# example={'tokens':exampletokens,'ner_tags':example_ner_tag}
# emaple_prepocessed=tokenize_and_align_labels(example)

In [190]:
from numpy import unique

unique(df_train.Typ1)

array(['B-LOC', 'B-LOCderiv', 'B-LOCpart', 'B-ORG', 'B-ORGderiv',
       'B-ORGpart', 'B-OTH', 'B-OTHderiv', 'B-OTHpart', 'B-PER',
       'B-PERderiv', 'B-PERpart', 'I-LOC', 'I-LOCderiv', 'I-LOCpart',
       'I-ORG', 'I-ORGpart', 'I-OTH', 'I-OTHderiv', 'I-OTHpart', 'I-PER',
       'I-PERderiv', 'I-PERpart', 'O'], dtype=object)

In [191]:
# tf_train_set = model.prepare_tf_dataset(
#     conll['train'].map(tokenize_and_align_labels, batched=True),
#     shuffle=True,
#     batch_size=1,
#     collate_fn=data_collator,
# )

In [192]:
#conll['train'][0]['pos_tags']

In [193]:
#conll['train'].features['pos_tags']


In [194]:
from keras.losses import BinaryCrossentropy, CategoricalCrossentropy, SparseCategoricalCrossentropy, Hinge
from transformers import TFAutoModelForTokenClassification, create_optimizer

'LMtraining'

model = TFAutoModelForTokenClassification.from_pretrained(model_name, num_labels=7,id2label={0:'O',1: 'B-PER', 2:'I-PER',3: 'B-ORG',4: 'I-ORG',5: 'B-LOC', 6:'I-LOC'}) #label2id
batch_size = 320
num_train_epochs = 30
num_train_steps = (len(conll['train']) // batch_size) * num_train_epochs
optimizer, lr_schedule = create_optimizer(
    init_lr=2e-5,
    num_train_steps=num_train_steps,
    weight_decay_rate=0.01,
    num_warmup_steps=0,
)

model.get_layer('bert').trainable=False
#SparseCategoricalCrossentropy(from_logits=True)


All model checkpoint layers were used when initializing TFBertForTokenClassification.

Some layers of TFBertForTokenClassification were not initialized from the model checkpoint at deepset/gbert-base and are newly initialized: ['classifier']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [195]:
model.compile(optimizer=optimizer,  metrics=["accuracy"])
#model.summary()

No loss specified in compile() - the model's internal loss computation will be used as the loss. Don't panic - this is a common way to train TensorFlow models in Transformers! To disable this behaviour please pass a loss argument, or explicitly pass `loss=None` if you do not want your model to compute a loss.


In [196]:
from transformers import DataCollatorForTokenClassification

data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer, return_tensors="tf")
tf_train_set = model.prepare_tf_dataset(
    conll['train'].map(tokenize_and_align_labels, batched=True),
    shuffle=False,
    batch_size=batch_size,
    collate_fn=data_collator,
)

tf_validation_set = model.prepare_tf_dataset(
    conll['validation'].map(tokenize_and_align_labels, batched=True),
    shuffle=True,
    batch_size=batch_size,
    collate_fn=data_collator,
)

  0%|          | 0/24 [00:00<?, ?ba/s]

You're using a BertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
C:\Users\Timo\PycharmProjects\shared-tasks-wintersemester-2022-23\venv\lib\site-packages\transformers\tokenization_utils_base.py:715: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  tensor = as_tensor(value)


  0%|          | 0/24 [00:00<?, ?ba/s]

In [ ]:
import numpy as np
import evaluate
seqeval = evaluate.load("seqeval")

def compute_metrics(p):

    #label_list = [0,1,2,3,4,5,6]
#
    label_list =ds['train'].features["ner_tags"].feature.names
    #label_list = tf_train_set.features[f"ner_tags"].feature.names

    predictions, labels = p
    predictions = np.argmax(predictions, axis=2)

    true_predictions = [
        [label_list[p] for (p, l) in zip(prediction, label) if l != -100]
        for prediction, label in zip(predictions, labels)
    ]
    true_labels = [
        [label_list[l] for (p, l) in zip(prediction, label) if l != -100]
        for prediction, label in zip(predictions, labels)
    ]

    results = seqeval.compute(predictions=true_predictions, references=true_labels)
    return {
        "precision": results["overall_precision"],
        "recall": results["overall_recall"],
        "f1": results["overall_f1"],
        "accuracy": results["overall_accuracy"],
    }


from transformers.keras_callbacks import KerasMetricCallback
metric_callback = KerasMetricCallback(metric_fn=compute_metrics, eval_dataset=tf_train_set)
model.compile(optimizer="adam",  # loss=keras.losses.CategoricalCrossentropy(from_logits=True),
                  metrics=['accuracy'])
#model.summary()
import os
os.environ["XLA_FLAGS"]="--xla_gpu_cuda_data_dir=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8"
model.fit(x=tf_train_set, validation_data=tf_train_set, epochs=100,callbacks=metric_callback)
#82,83

No loss specified in compile() - the model's internal loss computation will be used as the loss. Don't panic - this is a common way to train TensorFlow models in Transformers! To disable this behaviour please pass a loss argument, or explicitly pass `loss=None` if you do not want your model to compute a loss.


Epoch 1/100


C:\Users\Timo\PycharmProjects\shared-tasks-wintersemester-2022-23\venv\lib\site-packages\transformers\tokenization_utils_base.py:715: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  tensor = as_tensor(value)


75/75 [==============================] - 136s 2s/step - loss: 0.0830 - accuracy: 0.9804 - val_loss: 0.0621 - val_accuracy: 0.2840 - precision: 0.7541 - recall: 0.7943 - f1: 0.7737
Epoch 2/100
75/75 [==============================] - 121s 2s/step - loss: 0.0688 - accuracy: 0.9820 - val_loss: 0.0569 - val_accuracy: 0.2845 - precision: 0.7659 - recall: 0.8236 - f1: 0.7937
Epoch 3/100
75/75 [==============================] - 121s 2s/step - loss: 0.0651 - accuracy: 0.9828 - val_loss: 0.0542 - val_accuracy: 0.2847 - precision: 0.7741 - recall: 0.8312 - f1: 0.8017
Epoch 4/100
75/75 [==============================] - 120s 2s/step - loss: 0.0634 - accuracy: 0.9832 - val_loss: 0.0526 - val_accuracy: 0.2848 - precision: 0.7813 - recall: 0.8357 - f1: 0.8076
Epoch 5/100
75/75 [==============================] - 120s 2s/step - loss: 0.0624 - accuracy: 0.9835 - val_loss: 0.0515 - val_accuracy: 0.2849 - precision: 0.7835 - recall: 0.8419 - f1: 0.8117
Epoch 6/100
75/75 [==============================] -

In [293]:
import tensorflow as tf
# from huggingface
from transformers import AutoTokenizer

text="Kartoffel test ist eine schöne Stadt in München"
inputs_tokens = tokenizer(text, return_tensors="tf")

logits = model(**inputs_tokens).logits
#Get the class with the highest probability, and use the model’s id2label mapping to convert it to a text label:


predicted_token_class_ids = tf.math.argmax(logits, axis=-1)
print(predicted_token_class_ids)
predicted_token_class = [model.config.id2label[t] for t in predicted_token_class_ids[0].numpy().tolist()]
predicted_token_class


tf.Tensor([[0 0 0 0 0 0 0 0 1 0]], shape=(1, 10), dtype=int64)


['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-PER', 'O']

In [294]:
inputs_tokens

{'input_ids': <tf.Tensor: shape=(1, 10), dtype=int32, numpy=
array([[  102, 28410, 30028,   215,   261,  8668,   668,   153,  2591,
          103]])>, 'token_type_ids': <tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>, 'attention_mask': <tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])>}

In [295]:
subtoken=False

pred_labels=[]

ner_labels=[]
ner_labels_subtokens=[]
print('with subtokens')
for pred_label,subtoken in zip(predicted_token_class,inputs_tokens.input_ids.numpy()[0]):
    word=tokenizer.decode([subtoken])
    print("pred_label:", pred_label, " : ", subtoken, " : ", word)

print()
print('without subtokens')
for pred_label,subtoken in zip(predicted_token_class,inputs_tokens.input_ids.numpy()[0]):
    word=str(tokenizer.decode([subtoken]))



    if word[:2]== "##" :
        ner_labels_subtokens.append(pred_label)
        subtoken=True
    else:
        if subtoken==True:
            ner_labels.append(ner_labels_subtokens[0])
            ner_labels_subtokens=[]
            subtoken=False
        else:
            ner_labels.append(pred_label)
        print("pred_label:", pred_label, " : ", subtoken, " : ", word)


print(ner_labels)


with subtokens
pred_label: O  :  102  :  [CLS]
pred_label: O  :  28410  :  Kartoffel
pred_label: O  :  30028  :  test
pred_label: O  :  215  :  ist
pred_label: O  :  261  :  eine
pred_label: O  :  8668  :  schöne
pred_label: O  :  668  :  Stadt
pred_label: O  :  153  :  in
pred_label: B-PER  :  2591  :  München
pred_label: O  :  103  :  [SEP]

without subtokens
pred_label: O  :  102  :  [CLS]
pred_label: O  :  28410  :  Kartoffel
pred_label: O  :  30028  :  test
pred_label: O  :  215  :  ist
pred_label: O  :  261  :  eine
pred_label: O  :  8668  :  schöne
pred_label: O  :  668  :  Stadt
pred_label: O  :  153  :  in
pred_label: B-PER  :  2591  :  München
pred_label: O  :  103  :  [SEP]
['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-PER', 'O']


In [279]:
ner_labels_subtokens

[]

In [242]:
text="Kartoffel  Arschficken Arschficken Arschficken Kartoffel "
inputs = tokenizer(text, return_tensors="tf")
inputs

{'input_ids': <tf.Tensor: shape=(1, 13), dtype=int32, numpy=
array([[  102, 28410, 14359,  7838,   888, 14359,  7838,   888, 14359,
         7838,   888, 28410,   103]])>, 'token_type_ids': <tf.Tensor: shape=(1, 13), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>, 'attention_mask': <tf.Tensor: shape=(1, 13), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])>}

In [236]:
tokenizer.decode(inputs.input_ids.numpy()[0])

'[CLS] Kartoffel arschficken ist eine schöne Stadt in München [SEP]'

In [238]:
tokenizer.decode(inputs.tokens)

AttributeError: 'function' object has no attribute 'numpy'

In [233]:
inputs.input_ids.numpy()[0]


array([[ 102, 8668,  668,  153, 2591,  103]])

In [223]:
text = "Obama was the president of the United States and he was born in Hawai."

encoding = tokenizer(text, return_tensors="tf",is_split_into_words=True)
# forward pass
outputs = model(**encoding)
logits = outputs.logits
print(logits.shape)
predicted_label_classes = logits.argmax(-1)
print(predicted_label_classes)
predicted_labels = [model.config.id2label[id] for id in predicted_label_classes.squeeze().tolist()]
print(predicted_labels)
for id, label in zip(encoding.input_ids.squeeze().tolist(), predicted_labels):
  print(tokenizer.decode([id]), label)

TypeError: PreTokenizedEncodeInput must be Union[PreTokenizedInputSequence, Tuple[PreTokenizedInputSequence, PreTokenizedInputSequence]]

In [207]:
predicted_labels = [model.config.id2label[id] for id in predicted_token_class_ids[0].numpy().tolist()]
print(predicted_labels)

['O', 'O', 'O', 'O', 'B-PER', 'O']


In [216]:
for i in inputs.tokens:
    print(i)

TypeError: 'method' object is not iterable

In [217]:
inputs.tokens

<bound method BatchEncoding.tokens of {'input_ids': <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[ 102, 8668,  668,  153, 2591,  103]])>, 'token_type_ids': <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0]])>, 'attention_mask': <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1]])>}>

In [209]:
for id, label in zip(inputs.input_ids.tolist(), predicted_labels):
  print(tokenizer.decode([id]), label)

AttributeError: EagerTensor object has no attribute 'tolist'. 
        If you are looking for numpy-related methods, please run the following:
        from tensorflow.python.ops.numpy_ops import np_config
        np_config.enable_numpy_behavior()
      

In [212]:
inputs.input_ids.numpy()

array([[ 102, 8668,  668,  153, 2591,  103]])

In [202]:
tokenizer.decode(inputs)

TypeError: argument 'ids': 'dict' object cannot be converted to 'Sequence'

In [200]:
pred=model.predict(tf_train_set)


75/75 [==============================] - 39s 495ms/step


KeyboardInterrupt: 

In [ ]:


encoded=tokenizer(pred)
encoded.word_ids()
start,end=word_to_tokens(word_id)
tokenizer.decode()

In [ ]:

for example in tf_train_set:
   ainput_ids= example[0]['input_ids'].numpy()
   atoken_type_ids= example[0]['token_type_ids'].numpy()
   aattention_mask= example[0]['attention_mask'].numpy()
   alabels=example[1].numpy()
   print(example[1])
   break


In [ ]:
import os
os.environ["XLA_FLAGS"]="--xla_gpu_cuda_data_dir=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8"
model.fit(x=tf_train_set, validation_data=tf_validation_set, epochs=1)

In [ ]:
'detokenizer'


In [ ]:
# test prediction
pred=model.predict(tf_train_set)


In [ ]:
pred

In [ ]:
a=np.zeros(shape=(2))
compute_metrics(a)

In [ ]:
list=[]
for a in tf_train_set:
    list.append(a)

In [ ]:
a=example[0]['input_ids'][0]

tokenizer.decode(a)

In [ ]:
from numpy import argmax

id = 2

pred_label=[]
pred_sentence=[]
for pred_logits in pred.logits[id]:
    pred_sentence.append(argmax(pred_logits))

print(pred_sentence)
print(list[id][1][0].numpy())

In [ ]:
id=1

